#server.port=8080
#server.servlet.context-path=/eld_log

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=eld_log

spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=eld_log

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
spring.security.user.name=root
spring.security.user.password=$2a$04$FlHdRJcVCeC2hzQTzPs7XOPkBMn8h99GstJ5WxkKBZd2mXDSliY0K
spring.security.user.roles=USER

 spring.data.mongodb.auto-index-creation=true
 
 ## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

##email Configuration 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=serialcoder90@gmail.com
#spring.mail.password=Goal@2022
spring.mail.password=nsdzpghfotgwvnsa

# SSL, post 465
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory

#spring.mail.host=mail.incubatesoft.com
#spring.mail.port=587
#spring.mail.username=support@incubatesoft.com
#spring.mail.password=incsupport123

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR

cust.data.employee.name=Sachin

#spring.thymeleaf.prefix=classpath:/custom-templates/
#spring.thymeleaf.suffix=.html
#server.error.whitelabel.enabled=false
#spring.thymeleaf.cache=false

#schedulaar cron expressions
#<second> <minute> <hour> <day-of-month> <month> <day-of-week>//optional <year> <command>
#for scheduled emails : 11:59 PM everyday - ReportServiceImpl.java - scheduledReports()
#cron.expression=0 59 23 * * *
cron.expression=0 40 5 * * *
#Every second service started
cron.expression2=0 */1 * * * *
#to check, calculate and update the Trip Wise Revanue in IMobilityServiceServiceImpl - TripWiseRevanueServices() : Every 20th minute OR after every 20 minute 
cron.expression3=0 */10 * * * *
#to check, calculate and update the Trip Wise Revanue in IMobilityServiceServiceImpl - TripWiseRevanueServices() : 1st day of very month
cron.expression4=0 0 0 1 * ?
#temporary to check, calculate and update the substation loss record in CbismSubstationLogServiceImpl - alertOnSubstationLoss() : start of every day 
cron.expression5=0 0 0 * * *
#every day 2 AM Process report
cron.expression1=0 0 2 * * *
#every day 5 AM Process report
cron.expression7=0 0 5 * * *
#every 5 minutes process sevices
cron.expression6=0 */5 * * * *

cron.expression8=0 0 * * * ?

#spring.datasource.url=jdbc:mongodb://localhost:27017/imobility
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration   

##JPA configuration for iot database
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto= update
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#spring.datasource.hikari.connection-timeout=200000
#spring.datasource.hikari.minimum-idle=4
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.max-lifetime=1200000